version: '3.8'
services:
  app:
    image: notficationimage
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - notificacoes_data:/var/lib/postgresql/data

volumes:
  notificacoes_data:
    driver: local
